### ISSUE TITLE
gravatar 被墙了

### ISSUE THREAD

**Issue by AzusaCat1111** [applepi-icpc/UOJ-System#1]
如题，[这里](https://www.wpdaxue.com/gravatar-is-blocked.html)是搜到的一个解决方案（

**Comment by XYY1411** [comment]
> 如题，[这里](https://www.wpdaxue.com/gravatar-is-blocked.html)是搜到的一个解决方案（

emm，很早的事了，v2ex也被墙了，南校OJ头像也挂了

**Comment by renbaoshuo** [comment]
问题已在 #2 中解决，建议关闭本 issue 。

**Comment by XYY1411** [comment]
> 问题已在 #2 中解决，建议关闭本 issue 。

貌似没有部署上？现在还是 https://cn.gravatar.com/ 不科学上网仍然不可访问。

**Comment by applepi-icpc** [comment]
我刚才部署了新的代码了。建议测试一下之后关闭本 issue。

**Comment by XYY1411** [comment]
> 我刚才部署了新的代码了。建议测试一下之后关闭本 issue。

问题已解决，另外 AzusaCat 在准备国赛，应该没时间看 Github 来关闭 issue。
