### ISSUE TITLE
关于编译器与编译语言

### ISSUE THREAD

**Issue by XYY1411** [applepi-icpc/UOJ-System#5]
不知道是不是 S2OJ 更新到了 g++-9.3，现在选择语言 C++ 用的是 C++14，详见 [#15494](https://sjzezoj.com/submission/15496)， `__cplusplus` 的值是 `201402L`。

能不能把 C++ 编译选项加上 `-std=c++98`，然后增加 C++14，C++17 的语言？

**Comment by applepi-icpc** [comment]
这个问题已经有 PR 并且合并了。不过线上因为一些原因暂时没法上线，我们尽快上上去。
